{{- if not (empty (index .Values "alertmanager-webhook-adaptor" "configMapOverrideName")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "kubeblocks.labels" . | nindent 4 }}
  name: kb-addon-{{ include "addon.alertmanager-webhook-adaptor.name" . }}-{{index .Values "alertmanager-webhook-adaptor" "configMapOverrideName"}}
  namespace: {{ template "kubeblocks.prometheus.namespace" . }}
data:
  config.yml: |
    receivers: [ ]
{{- end -}}