---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: backupjobs.dataprotection.infracreate.com
spec:
  group: dataprotection.infracreate.com
  names:
    categories:
    - dbaas
    kind: BackupJob
    listKind: BackupJobList
    plural: backupjobs
    singular: backupjob
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .status.completionTimestamp
      name: CompletionTime
      type: date
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BackupJob is the Schema for the backupjobs API (defined by User)
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BackupJobSpec defines the desired state of BackupJob
            properties:
              backupPolicyName:
                description: which backupPolicy to perform this backupJob
                type: string
              backupType:
                default: full
                description: Backup Type. full or incremental. if unset, default is
                  full.
                enum:
                - full
                - incremental
                type: string
              parentBackupJobName:
                description: if backupType is incremental, parentBackupName is required.
                type: string
              ttl:
                description: TTL is a time.Duration-parsable string describing how
                  long the Backup should be retained for.
                type: string
            required:
            - backupPolicyName
            - backupType
            type: object
          status:
            description: BackupJobStatus defines the observed state of BackupJob
            properties:
              CheckPoint:
                description: backup check point, for incremental backup.
                type: string
              checkSum:
                description: checksum of backup file, generated by md5 or sha1 or
                  sha256
                type: string
              completionTimestamp:
                description: Date/time when the backup finished being processed.
                format: date-time
                type: string
              expiration:
                description: The date and time when the Backup is eligible for garbage
                  collection. 'null' means the Backup is NOT be cleaned except delete
                  manual.
                format: date-time
                type: string
              failureReason:
                description: the reason if backup failed.
                type: string
              parentBackupJobName:
                description: record parentBackupJobName if backupType is incremental.
                type: string
              phase:
                description: BackupJobPhase The current phase. Valid values are New,
                  InProgress, Completed, Failed.
                type: string
              startTimestamp:
                description: Date/time when the backup started being processed.
                format: date-time
                type: string
              totalSize:
                description: backup total size
                type: string
              uploadTotalSize:
                description: backup total size
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
