apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.1
  labels:
    app.kubernetes.io/name: kubeblocks
  name: otelds.monitor.kubeblocks.io
spec:
  group: monitor.kubeblocks.io
  names:
    kind: OTeld
    listKind: OTeldList
    plural: otelds
    singular: oteld
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: OTeld is the Schema for the collectordatasources API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OTeldSpec defines the desired state of CollectorDataSource
            properties:
              batch:
                properties:
                  enabled:
                    type: boolean
                type: object
              collectionInterval:
                description: CollectionInterval is the default collect interval of
                  the oteld collection
                type: string
              image:
                description: Image is the image of the oteld
                type: string
              logLevel:
                description: LogsLevel is the level of the oteld collector logs
                type: string
              memeryLimit:
                properties:
                  enabled:
                    description: MemoryLimit is the memory limit of the oteld
                    type: boolean
                type: object
              metricsPort:
                description: MetricsPort is the port of the oteld metrics
                type: integer
              mode:
                description: Mode represents how the OTeld should be deployed (deployment,
                  daemonset, statefulset or sidecar)
                enum:
                - daemonset
                - deployment
                - sidecar
                - statefulset
                type: string
              nodeSelector:
                additionalProperties:
                  type: string
                description: NodeSelector to schedule OpenTelemetry Collector pods.
                  This is only relevant to daemonset, statefulset, and deployment
                  mode
                type: object
              resources:
                description: Resources is the resource requirements for the oteld
                properties:
                  claims:
                    description: "Claims lists the names of resources, defined in
                      spec.resourceClaims, that are used by this container. \n This
                      is an alpha field and requires enabling the DynamicResourceAllocation
                      feature gate. \n This field is immutable. It can only be set
                      for containers."
                    items:
                      description: ResourceClaim references one entry in PodSpec.ResourceClaims.
                      properties:
                        name:
                          description: Name must match the name of one entry in pod.spec.resourceClaims
                            of the Pod where this field is used. It makes that resource
                            available inside a container.
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                    x-kubernetes-list-map-keys:
                    - name
                    x-kubernetes-list-type: map
                  limits:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: 'Limits describes the maximum amount of compute resources
                      allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                    type: object
                  requests:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: 'Requests describes the minimum amount of compute
                      resources required. If Requests is omitted for a container,
                      it defaults to Limits if that is explicitly specified, otherwise
                      to an implementation-defined value. Requests cannot exceed Limits.
                      More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                    type: object
                type: object
              useConfigMap:
                description: UseConfigMap indicates whether to use configmap to store
                  oteld config
                type: boolean
            required:
            - collectionInterval
            - useConfigMap
            type: object
          status:
            description: OTeldStatus defines the observed state of CollectorDataSource
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
