apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-create-{{- include "foxlake-cluster.postJobName" . -}}-bucket-post-job"
  labels: {{ include "foxlake-cluster.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-create-{{- include "foxlake-cluster.postJobName" . -}}-bucket"
      labels: {{ include "foxlake-cluster.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- if eq (include "foxlake-cluster.deployEnv" .) "local" }}
      initContainers:
        - name: wait-for-minio
          image: "busybox:latest"
          command:
            - "sh"
            - "-c"
            - "while ! nc -z ${MINIO_FQDN} 9000; do sleep 1; printf '-'; done; echo -e '  >> Minio Server has started';"
          env:
            {{- include "foxlake-cluster.postJobEnv" . | nindent 12}}
      {{- end }}
      containers:
        - name: create-{{- include "foxlake-cluster.postJobName" . -}}-bucket
          image: 
            {{- include "foxlake-cluster.postJobImage" . | nindent 12}}
          command:
            - "/scripts/create_{{- include "foxlake-cluster.postJobName" . -}}_bucket.sh"
          env:
            {{- include "foxlake-cluster.postJobEnv" . | nindent 12}}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: foxlake-cluster-setup-scripts 
            defaultMode: 0777
  backoffLimit: 0