# Default values for bytebase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
images:
  registry: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com
  bytebase:
    # if the value of images.bytebase.registry is not specified using `--set`, it will be set to the value of 'image.registry' by default
    registry: ""
    repository: apecloud/bytebase
    tag: beta1
    pullPolicy: IfNotPresent
  python:
    # if the value of images.python.registry is not specified using `--set`, it will be set to the value of 'image.registry' by default
    registry: ""
    repository: apecloud/python11-tools
    tag: stable
    pullPolicy: ""


bytebase:
  option:
    port: 8080
    existingPgURLSecret: ""
    existingPgURLSecretKey: ""
    pg:
    data: /var/opt/bytebase
    external-url: "https://www.bytebase.com/docs/get-started/install/external-url"
    disable-sample: false
  version: 2.5.0
  registryMirrorHost: ""
  persistence:
    storage: 2Gi
    enabled: false
    storageClass: ""
    existingClaim: ""
