# Default values for mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: mongo # docker.io/bitnami/mongodb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 5.0.14 # 6.0.3-debian-11-r0

clusterVersionOverride: ""
nameOverride: ""
fullnameOverride: ""

roleProbe:
  failureThreshold: 3
  periodSeconds: 2
  timeoutSeconds: 1

## Authentication parameters
##
auth:
  ## @param auth.password Password for the "mongodb" admin user, leave empty 
  ## for random generated password.
  ##
  password:
  ## @param auth.database Name for a custom database to create
  ##
  database: "admin"

logConfigs:
  running: /data/mongodb/logs/mongodb.log*

metrics:
  image:
    registry: registry.cn-hangzhou.aliyuncs.com
    repository: apecloud/agamotto
    tag: 0.1.0-beta.3
    pullPolicy: IfNotPresent
  config:
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
        path: /health/status
        check_collector_pipeline:
          enabled: true
          interval: 2m
          exporter_failure_threshold: 5

    receivers:
      apecloudmongodb:
        endpoint: 127.0.0.1:27017
        username: ${env:MONGODB_ROOT_USER}
        password: ${env:MONGODB_ROOT_PASSWORD}
        connect_params: admin?ssl=false&authSource=admin
        collect_all: true
        collection_interval: 15s
        direct_connect: true
        global_conn_pool: false
        compatible_mode: true

    processors:
      batch:
        timeout: 5s
      memory_limiter:
        limit_mib: 1024
        spike_limit_mib: 256
        check_interval: 10s

    exporters:
      prometheus:
        endpoint: 0.0.0.0:9216
        const_labels: [ ]
        send_timestamps: false
        metric_expiration: 30s
        enable_open_metrics: false
        resource_to_telemetry_conversion:
          enabled: true

    service:
      telemetry:
        logs:
          level: info
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        metrics:
          receivers: [apecloudmongodb]
          processors: [memory_limiter]
          exporters: [prometheus]

      extensions: [health_check]
