apiVersion: v2
name: redis
description: A Redis cluster definition Helm chart for Kubernetes

type: application

version: 0.5.0-beta.9

appVersion: "7.0.6"

home: https://redis.io/
icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
  - redis
  - database
  - nosql
  - replication

maintainers:
  - name: ApeCloud
    url: https://github.com/apecloud/kubeblocks/deploy