apiVersion: v2
name: oceanbase
description: "Unlimited scalable distributed database for data-intensive transactional and real-time operational analytics workloads, with ultra-fast performance that has once achieved world records in the TPC-C benchmark test. OceanBase has served over 400 customers across the globe and has been supporting all mission critical systems in Alipay."

type: application

version: 0.0.1-alpha1

appVersion: "4.2.0.0-100010032023083021"
