---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: componentclassdefinitions.apps.kubeblocks.io
spec:
  group: apps.kubeblocks.io
  names:
    categories:
    - kubeblocks
    kind: ComponentClassDefinition
    listKind: ComponentClassDefinitionList
    plural: componentclassdefinitions
    shortNames:
    - ccd
    singular: componentclassdefinition
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ComponentClassDefinition is the Schema for the componentclassdefinitions
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ComponentClassDefinitionSpec defines the desired state of
              ComponentClassDefinition
            properties:
              groups:
                description: group defines a list of class series that conform to
                  the same constraint.
                items:
                  properties:
                    series:
                      description: series is a series of class definitions.
                      items:
                        properties:
                          classes:
                            description: classes are definitions of classes that come
                              in two forms. In the first form, only ComponentClass.Args
                              need to be defined, and the complete class definition
                              is generated by rendering the ComponentClassGroup.Template
                              and Name. In the second form, the Name, CPU and Memory
                              must be defined.
                            items:
                              properties:
                                args:
                                  description: args are variable's value
                                  items:
                                    type: string
                                  type: array
                                cpu:
                                  anyOf:
                                  - type: integer
                                  - type: string
                                  description: the CPU of the class
                                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                  x-kubernetes-int-or-string: true
                                memory:
                                  anyOf:
                                  - type: integer
                                  - type: string
                                  description: the memory of the class
                                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                  x-kubernetes-int-or-string: true
                                name:
                                  description: name is the class name
                                  type: string
                              type: object
                            type: array
                          namingTemplate:
                            description: 'namingTemplate is a template that uses the
                              Go template syntax and allows for referencing variables
                              defined in ComponentClassGroup.Template. This enables
                              dynamic generation of class names. For example: name:
                              "general-{{ .cpu }}c{{ .memory }}g"'
                            type: string
                        type: object
                      type: array
                    template:
                      description: "template is a class definition template that uses
                        the Go template syntax and allows for variable declaration.
                        When defining a class in Series, specifying the variable's
                        value is sufficient, as the complete class definition will
                        be generated through rendering the template. \n For example:
                        template: | cpu: \"{{ or .cpu 1 }}\" memory: \"{{ or .memory
                        4 }}Gi\""
                      type: string
                    vars:
                      description: vars defines the variables declared in the template
                        and will be used to generating the complete class definition
                        by render the template.
                      items:
                        type: string
                      type: array
                      x-kubernetes-list-type: set
                  type: object
                type: array
            type: object
          status:
            description: ComponentClassDefinitionStatus defines the observed state
              of ComponentClassDefinition
            properties:
              classes:
                description: classes is the list of classes that have been observed
                  for this ComponentClassDefinition
                items:
                  properties:
                    args:
                      description: args are variable's value
                      items:
                        type: string
                      type: array
                    cpu:
                      anyOf:
                      - type: integer
                      - type: string
                      description: the CPU of the class
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    memory:
                      anyOf:
                      - type: integer
                      - type: string
                      description: the memory of the class
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    name:
                      description: name is the class name
                      type: string
                  type: object
                type: array
              observedGeneration:
                description: observedGeneration is the most recent generation observed
                  for this ComponentClassDefinition. It corresponds to the ComponentClassDefinition's
                  generation, which is updated on mutation by the API Server.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
