# Default values for vllm-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @param version vllm cluster version
##
version: vllm-baichuan2-13b

## @param replicas specify cluster replicas
##
replicas: 1

## @param cpu
##
cpu: 0.5

## @param memory, the unit is Gi
##
memory: 0.5

## @param storage size, the unit is Gi
##
storage: 20

## @param gpu
##
gpu: 1