apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: mysql
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: mysql
  connectionCredential:
    username: root
    password: "$(RANDOM_PASSWD)"
    endpoint: "$(SVC_FQDN):$(SVC_PORT_mysql)"
    host: "$(SVC_FQDN)"
    port: "$(SVC_PORT_mysql)"
  componentDefs:
    - name: mysql
      characterType: mysql
      probes:
        roleProbe:
          failureThreshold: {{ .Values.roleProbe.failureThreshold }}
          periodSeconds: {{ .Values.roleProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.roleProbe.timeoutSeconds }}
      workloadType: Replication
      service:
        ports:
          - name: mysql
            port: 3306
            targetPort: mysql
      monitor:
        builtIn: false
        exporterConfig:
          scrapePath: /metrics
          scrapePort: {{ .Values.metrics.service.port }}
      configSpecs:
        - name: mysql-replication-config
          templateRef: mysql8.0.33-config-template
          constraintRef: mysql8.0.33-config-constraints
          volumeName: mysql-config
          namespace: {{ .Release.Namespace }}
        - name: agamotto-configuration
          templateRef: mysql-agamotto-configuration
          namespace: {{ .Release.Namespace }}
          volumeName: agamotto-configuration
          defaultMode: 0777
      scriptSpecs:
        - name: mysql-scripts
          templateRef: mysql-scripts
          namespace: {{ .Release.Namespace }}
          volumeName: scripts
          defaultMode: 493
      volumeTypes:
        - name: data
          type: data
      podSpec:
        containers:
          - name: mysql
            imagePullPolicy: IfNotPresent
            command:
              - bash 
              - -c
              - "docker-entrypoint.sh mysqld --server-id $(( ${KB_POD_NAME##*-} + 1))"
            volumeMounts:
              - mountPath: /var/lib/mysql
                name: data
              - mountPath: /etc/mysql/conf.d
                name: mysql-config
            ports:
              - containerPort: 3306
                name: mysql
            env:
              - name: MYSQL_ROOT_HOST
                value: {{ .Values.auth.rootHost | default "%" | quote }}
              - name: MYSQL_ROOT_USER
                valueFrom:
                  secretKeyRef:
                    name: $(CONN_CREDENTIAL_SECRET_NAME)
                    key: username
                    optional: false
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: $(CONN_CREDENTIAL_SECRET_NAME)
                    key: password
                    optional: false
          - name: metrics
            image:  {{ .Values.metrics.image.registry | default "docker.io" }}/{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
            imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
            env:
              - name: DB_TYPE
                value: MySQL
              - name: ENDPOINT
                value: "localhost:3306"
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: $(CONN_CREDENTIAL_SECRET_NAME)
                    key: username
                    optional: false
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: $(CONN_CREDENTIAL_SECRET_NAME)
                    key: password
                    optional: false
            command: ["/scripts/agamotto.sh"]
            ports:
              - name: http-metrics
                containerPort: {{ .Values.metrics.service.port }}
            volumeMounts:
              - name: agamotto-configuration
                mountPath: /opt/agamotto
              - name: data
                mountPath: /data/mysql
              - name: log-data
                mountPath: /var/log/kubeblocks
                readOnly: false
              - name: scripts
                mountPath: /scripts
