---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-workloads-kubeblocks-io-v1alpha1-instanceset
  failurePolicy: Fail
  name: minstanceset.kb.io
  rules:
  - apiGroups:
    - workloads.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instancesets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-kubeblocks-io-v1alpha1-clusterdefinition
  failurePolicy: Fail
  name: mclusterdefinition.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterdefinitions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-kubeblocks-io-v1alpha1-component
  failurePolicy: Fail
  name: mcomponent.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - components
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-kubeblocks-io-v1alpha1-componentdefinition
  failurePolicy: Fail
  name: mcomponentdefinition.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componentdefinitions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-kubeblocks-io-v1alpha1-componentversion
  failurePolicy: Fail
  name: mcomponentversion.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componentversions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-kubeblocks-io-v1alpha1-servicedescriptor
  failurePolicy: Fail
  name: mservicedescriptor.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicedescriptors
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-kubeblocks-io-v1-configconstraint
  failurePolicy: Fail
  name: vconfigconstraint.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configconstraints
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-workloads-kubeblocks-io-v1alpha1-instanceset
  failurePolicy: Fail
  name: vinstanceset.kb.io
  rules:
  - apiGroups:
    - workloads.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instancesets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-kubeblocks-io-v1alpha1-cluster
  failurePolicy: Fail
  name: vcluster.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-kubeblocks-io-v1alpha1-clusterdefinition
  failurePolicy: Fail
  name: vclusterdefinition.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterdefinitions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-kubeblocks-io-v1alpha1-component
  failurePolicy: Fail
  name: vcomponent.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - components
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-kubeblocks-io-v1alpha1-componentdefinition
  failurePolicy: Fail
  name: vcomponentdefinition.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componentdefinitions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-kubeblocks-io-v1alpha1-componentversion
  failurePolicy: Fail
  name: vcomponentversion.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componentversions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-kubeblocks-io-v1alpha1-opsrequest
  failurePolicy: Fail
  name: vopsrequest.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opsrequests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-kubeblocks-io-v1alpha1-servicedescriptor
  failurePolicy: Fail
  name: vservicedescriptor.kb.io
  rules:
  - apiGroups:
    - apps.kubeblocks.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicedescriptors
  sideEffects: None
