apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: clickhouse
  labels:
    {{- include "kubeblocks.labels" . | nindent 4 }}
    "kubeblocks.io/provider": community
  {{- if .Values.keepAddons }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  description: 'ClickHouse is an open-source column-oriented OLAP database management
  system. Use it to boost your database performance while providing linear scalability
  and hardware efficiency.'

  type: Helm

  helm:
    {{- include "kubeblocks.addonChartLocationURL" ( dict "name" "risingwave" "version" (default .Chart.Version .Values.versionOverride) "values" .Values) | indent 4 }}
    {{- include "kubeblocks.addonChartsImage" . | indent 4 }}

    installOptions:
     {{- if hasPrefix "oci://" .Values.addonChartLocationBase }}
      version: {{ default .Chart.Version .Values.versionOverride }}
     {{- end }}

  installable:
    autoInstall: false

  defaultInstallValues:
    - enabled: true
