{{- include "kubeblocks.buildAddonCR" (merge (dict
  "kbVersion" ">=0.7.0"
  "name" "mariadb"
  "version" "0.7.0"
  "model" "RDBMS"
  "provider" "community"
  "description" "Mariadb is a widely used, open-source relational database management system (RDBMS)."
  "autoInstall" false) . ) -}}