{{- include "kubeblocks.buildAddonCR" (merge (dict
  "kbVersion" ">=0.7.0"
  "name" "orioledb"
  "version" "0.8.0-alpha.5"
  "model" "RDBMS"
  "provider" "apecloud"
  "description" "OrioleDB â€“ a modern cloud-native storage engine solving some PostgreSQL wicked problems."
  "autoInstall" false) . ) -}}
