{{- if has "qdrant" .Values.autoInstalledAddons  }}
{{- $selectorLabels := include "kubeblocks.selectorLabels" . }}
{{- include "kubeblocks.buildAddonCR" (merge (dict
  "kbVersion" ">=0.7.0"
  "selectorLabels" $selectorLabels
  "name" "qdrant"
  "version" "0.9.1"
  "model" "vector"
  "provider" "community"
  "description" "Qdrant is an open source (Apache-2.0 licensed), vector similarity search engine and vector database."
  "autoInstall" false) . ) -}}
{{- end }}