{{- include "kubeblocks.buildAddonCR" (merge (dict
  "kbVersion" ">=0.7.0"
  "name" "zookeeper"
  "version" "0.7.0"
  "model" "other"
  "provider" "community"
  "description" "Apache ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services."
  "autoInstall" false) . ) -}}