apiVersion: apps.kubeblocks.io/v1alpha1
kind: BackupPolicyTemplate
metadata:
  name: milvus-backup-policy-template
  labels:
    clusterdefinition.kubeblocks.io/name: milvus
    {{- include "milvus.labels" . | nindent 4 }}
spec:
  clusterDefinitionRef: milvus
  backupPolicies:
  - componentDefRef: milvus
    backupMethods:
    - name: volume-snapshot
      snapshotVolumes: true
      targetVolumes:
        volumes:
        - data
    schedules:
    - backupMethod: volume-snapshot
      retentionPeriod: 7d
      enabled: false
      cronExpression: "0 18 * * 0"