## staticParameters, list of StaticParameter, modifications of them trigger a process restart.
## dynamicParameters, list of DynamicParameter, modifications of them trigger a config dynamic reload without process restart.
## staticParameters and dynamicParameters determine the behavior of parameter changes:
## if any of the modified parameters is in the staticParameters list, this operation will trigger a process restart.
## if all the changed parameters are in the dynamicParameters list, this change executes reload without process restart.
## if the above two conditions are not met, by default, parameter change operation follow the rule for using staticParameters.
staticParameters:
  - xengine
  - smartengine
  - loose_smartengine
  - allow-suspicious-udfs
  - auto_generate_certs
  - back_log
  - basedir
  - bind_address
  - binlog_gtid_simple_recovery
  - caching_sha2_password_auto_generate_rsa_keys
  - caching_sha2_password_private_key_path
  - caching_sha2_password_public_key_path
  - character-set-client-handshake
  - character_sets_dir
  - core-file
  - datadir
  - default_authentication_plugin
  - default_time_zone
  - disabled_storage_engines
  - disconnect_on_expired_password
  - enforce_gtid_consistency
  - explicit_defaults_for_timestamp
  - ft_max_word_len
  - ft_min_word_len
  - ft_query_expansion_limit
  - ft_stopword_file
  - gtid-mode
  - gtid_owned
  - init_file
  - innodb_adaptive_hash_index_parts
  - innodb_autoinc_lock_mode
  - innodb_buffer_pool_chunk_size
  - innodb_buffer_pool_instances
  - innodb_buffer_pool_load_at_startup
  - innodb_commit_concurrency
  - innodb_data_file_path
  - innodb_data_home_dir
  - innodb_dedicated_server
  - innodb_directories
  - innodb_doublewrite
  - innodb_doublewrite_files
  - innodb_doublewrite_pages
  - innodb_flush_method
  - innodb_force_load_corrupted
  - innodb_force_recovery
  - innodb_ft_cache_size
  - innodb_ft_max_token_size
  - innodb_ft_min_token_size
  - innodb_ft_sort_pll_degree
  - innodb_ft_total_cache_size
  - innodb_log_files_in_group
  - innodb_log_file_size
  - innodb_log_group_home_dir
  - innodb_open_files
  - innodb_page_cleaners
  - innodb_page_size
  - innodb_purge_threads
  - innodb_read_io_threads
  - innodb_read_only
  - innodb_rollback_on_timeout
  - innodb_scan_directories
  - innodb_sort_buffer_size
  - innodb_stats_include_delete_marked
  - innodb_sync_array_size
  - innodb_temp_data_file_path
  - innodb_undo_directory
  - innodb_undo_tablespaces
  - innodb_use_native_aio
  - innodb_write_io_threads
  - large_pages
  - log_bin
  - log-bin
  - log_bin_basename
  - log_bin_index
  - log_bin_use_v1_row_events
  - log_error
  - log_slave_updates
  - lower_case_file_system
  - lower_case_table_names
  - master-info-repository
  - max_digest_length
  - mecab_rc_file
  - myisam_mmap_size
  - mysqlx_bind_address
  - mysqlx_port
  - mysqlx_port_open_timeout
  - mysqlx_socket
  - mysqlx_ssl_ca
  - mysqlx_ssl_capath
  - mysqlx_ssl_cert
  - mysqlx_ssl_crl
  - mysqlx_ssl_crlpath
  - mysqlx_ssl_key
  - ngram_token_size
  - old-style-user-limits
  - open_files_limit
  - performance_schema
  - performance_schema_accounts_size
  - performance_schema_digests_size
  - performance_schema_error_size
  - performance_schema_events_stages_history_long_size
  - performance_schema_events_stages_history_size
  - performance_schema_events_statements_history_long_size
  - performance_schema_events_statements_history_size
  - performance_schema_events_transactions_history_long_size
  - performance_schema_events_transactions_history_size
  - performance_schema_events_waits_history_long_size
  - performance_schema_events_waits_history_size
  - performance_schema_hosts_size
  - performance_schema_max_cond_classes
  - performance_schema_max_cond_instances
  - performance_schema_max_digest_length
  - performance_schema_max_file_classes
  - performance_schema_max_file_handles
  - performance_schema_max_file_instances
  - performance_schema_max_index_stat
  - performance_schema_max_memory_classes
  - performance_schema_max_metadata_locks
  - performance_schema_max_mutex_classes
  - performance_schema_max_mutex_instances
  - performance_schema_max_prepared_statements_instances
  - performance_schema_max_program_instances
  - performance_schema_max_rwlock_classes
  - performance_schema_max_rwlock_instances
  - performance_schema_max_socket_classes
  - performance_schema_max_socket_instances
  - performance_schema_max_sql_text_length
  - performance_schema_max_stage_classes
  - performance_schema_max_statement_classes
  - performance_schema_max_statement_stack
  - performance_schema_max_table_handles
  - performance_schema_max_table_instances
  - performance_schema_max_table_lock_stat
  - performance_schema_max_thread_classes
  - performance_schema_max_thread_instances
  - performance_schema_session_connect_attrs_size
  - performance_schema_setup_actors_size
  - performance_schema_setup_objects_size
  - performance_schema_users_size
  - persisted_globals_load
  - pid_file
  - plugin_dir
  - port
  - protocol_version
  - rds.optimized_writes
  - relay_log
  - relay-log
  - relay_log_basename
  - relay_log_index
  - relay_log_info_file
  - relay_log_info_repository
  - relay_log_space_limit
  - report_host
  - report_password
  - report_port
  - report_user
  - safe-user-create
  - secure_file_priv
  - sha256_password_auto_generate_rsa_keys
  - sha256_password_private_key_path
  - sha256_password_public_key_path
  - skip-character-set-client-handshake
  - skip_external_locking
  - skip_name_resolve
  - skip_show_database
  - skip-slave-start
  - slave_load_tmpdir
  - slave_parallel_type
  - slave_type_conversions
  - socket
  - ssl_ca
  - ssl_capath
  - ssl_cert
  - ssl_cipher
  - ssl_crl
  - ssl_crlpath
  - ssl_key
  - sysdate-is-now
  - system_time_zone
  - table_open_cache_instances
  - temptable_max_mmap
  - thread_handling
  - thread_stack
  - tls_version
  - tmpdir
  - validate-password
  - validate_password_dictionary_file
  - version_comment
  - version_compile_machine
  - version_compile_os
  - version_compile_zlib

dynamicParameters:
  - activate_all_roles_on_login
  - autocommit
  - auto_increment_increment
  - auto_increment_offset
  - automatic_sp_privileges
  - avoid_temporal_upgrade
  - big_tables
  - binlog_cache_size
  - binlog_checksum
  - binlog_direct_non_transactional_updates
  - binlog_error_action
  - binlog_expire_logs_seconds
  - binlog_format
  - binlog_group_commit_sync_delay
  - binlog_group_commit_sync_no_delay_count
  - binlog_max_flush_queue_time
  - binlog_order_commits
  - binlog_row_image
  - binlog_row_metadata
  - binlog_rows_query_log_events
  - binlog_row_value_options
  - binlog_stmt_cache_size
  - binlog_transaction_dependency_history_size
  - binlog_transaction_dependency_tracking
  - block_encryption_mode
  - bulk_insert_buffer_size
  - character_set_client
  - character_set_connection
  - character_set_database
  - character_set_filesystem
  - character_set_results
  - character_set_server
  - check_proxy_users
  - collation_connection
  - collation_database
  - collation_server
  - completion_type
  - concurrent_insert
  - connect_timeout
  - cte_max_recursion_depth
  - default_collation_for_utf8mb4
  - default_password_lifetime
  - default_storage_engine
  - default_tmp_storage_engine
  - default_week_format
  - delayed_insert_limit
  - delayed_insert_timeout
  - delayed_queue_size
  - delay_key_write
  - div_precision_increment
  - end_markers_in_json
  - eq_range_index_dive_limit
  - event_scheduler
  - expire_logs_days
  - flush
  - flush_time
  - foreign_key_checks
  - ft_boolean_syntax
  - general_log
  - general_log_file
  - group_concat_max_len
  - gtid_executed_compression_period
  - gtid_mode
  - gtid_purged
  - histogram_generation_max_mem_size
  - host_cache_size
  - information_schema_stats_expiry
  - init_connect
  - init_slave
  - innodb_adaptive_flushing
  - innodb_adaptive_flushing_lwm
  - innodb_adaptive_hash_index
  - innodb_adaptive_max_sleep_delay
  - innodb_autoextend_increment
  - innodb_buffer_pool_dump_at_shutdown
  - innodb_buffer_pool_dump_now
  - innodb_buffer_pool_dump_pct
  - innodb_buffer_pool_filename
  - innodb_buffer_pool_load_abort
  - innodb_buffer_pool_load_now
  - innodb_buffer_pool_size
  - innodb_change_buffering
  - innodb_change_buffer_max_size
  - innodb_checkpoint_disabled
  - innodb_checksum_algorithm
  - innodb_cmp_per_index_enabled
  - innodb_compression_failure_threshold_pct
  - innodb_compression_level
  - innodb_compression_pad_pct_max
  - innodb_concurrency_tickets
  - innodb_ddl_log_crash_reset_debug
  - innodb_deadlock_detect
  - innodb_default_row_format
  - innodb_disable_sort_file_cache
  - innodb_doublewrite_batch_size
  - innodb_fast_shutdown
  - innodb_file_per_table
  - innodb_fill_factor
  - innodb_flushing_avg_loops
  - innodb_flush_log_at_timeout
  - innodb_flush_log_at_trx_commit
  - innodb_flush_neighbors
  - innodb_flush_sync
  - innodb_ft_aux_table
  - innodb_ft_enable_diag_print
  - innodb_ft_enable_stopword
  - innodb_ft_num_word_optimize
  - innodb_ft_result_cache_limit
  - innodb_ft_server_stopword_table
  - innodb_ft_user_stopword_table
  - innodb_io_capacity
  - innodb_io_capacity_max
  - innodb_lock_wait_timeout
  - innodb_log_buffer_size
  - innodb_log_checksums
  - innodb_log_compressed_pages
  - innodb_log_spin_cpu_abs_lwm
  - innodb_log_spin_cpu_pct_hwm
  - innodb_log_wait_for_flush_spin_hwm
  - innodb_log_write_ahead_size
  - innodb_lru_scan_depth
  - innodb_max_dirty_pages_pct
  - innodb_max_dirty_pages_pct_lwm
  - innodb_max_purge_lag
  - innodb_max_purge_lag_delay
  - innodb_max_undo_log_size
  - innodb_monitor_disable
  - innodb_monitor_enable
  - innodb_monitor_reset
  - innodb_monitor_reset_all
  - innodb_old_blocks_pct
  - innodb_old_blocks_time
  - innodb_online_alter_log_max_size
  - innodb_optimize_fulltext_only
  - innodb_parallel_read_threads
  - innodb_print_all_deadlocks
  - innodb_print_ddl_logs
  - innodb_purge_batch_size
  - innodb_purge_rseg_truncate_frequency
  - innodb_random_read_ahead
  - innodb_read_ahead_threshold
  - innodb_redo_log_encrypt
  - innodb_replication_delay
  - innodb_rollback_segments
  - innodb_segment_reserve_factor
  - innodb_spin_wait_delay
  - innodb_stats_auto_recalc
  - innodb_stats_method
  - innodb_stats_on_metadata
  - innodb_stats_persistent
  - innodb_stats_persistent_sample_pages
  - innodb_stats_transient_sample_pages
  - innodb_status_output
  - innodb_status_output_locks
  - innodb_strict_mode
  - innodb_sync_spin_loops
  - innodb_table_locks
  - innodb_thread_concurrency
  - innodb_thread_sleep_delay
  - innodb_tmpdir
  - innodb_undo_log_encrypt
  - innodb_undo_log_truncate
  - interactive_timeout
  - internal_tmp_mem_storage_engine
  - join_buffer_size
  - keep_files_on_create
  - key_buffer_size
  - key_cache_age_threshold
  - key_cache_block_size
  - key_cache_division_limit
  - keyring_operations
  - lc_messages
  - lc_messages_dir
  - lc_time_names
  - local_infile
  - lock_wait_timeout
  - log_bin_trust_function_creators
  - log_error_services
  - log_error_verbosity
  - log_output
  - log_queries_not_using_indexes
  - log_slow_admin_statements
  - log_slow_extra
  - log_slow_slave_statements
  - log_statements_unsafe_for_binlog
  - log_syslog
  - log_throttle_queries_not_using_indexes
  - log_timestamps
  - long_query_time
  - low_priority_updates
  - mandatory_roles
  - master_info_repository
  - master_verify_checksum
  - max_allowed_packet
  - max_binlog_cache_size
  - max_binlog_size
  - max_binlog_stmt_cache_size
  - max_connect_errors
  - max_connections
  - max_delayed_threads
  - max_error_count
  - max_execution_time
  - max_heap_table_size
  - max_insert_delayed_threads
  - max_join_size
  - max_length_for_sort_data
  - max_points_in_geometry
  - max_prepared_stmt_count
  - max_relay_log_size
  - max_seeks_for_key
  - max_sort_length
  - max_sp_recursion_depth
  - max_user_connections
  - max_write_lock_count
  - min_examined_row_limit
  - myisam_data_pointer_size
  - myisam_max_sort_file_size
  - myisam_repair_threads
  - myisam_sort_buffer_size
  - myisam_stats_method
  - myisam_use_mmap
  - mysql_native_password_proxy_users
  - mysqlx_connect_timeout
  - mysqlx_document_id_unique_prefix
  - mysqlx_idle_worker_thread_timeout
  - mysqlx_interactive_timeout
  - mysqlx_max_allowed_packet
  - mysqlx_max_connections
  - mysqlx_min_worker_threads
  - mysqlx_read_timeout
  - mysqlx_wait_timeout
  - mysqlx_write_timeout
  - net_buffer_length
  - net_read_timeout
  - net_retry_count
  - net_write_timeout
  - new
  - offline_mode
  - old_alter_table
  - optimizer_prune_level
  - optimizer_search_depth
  - optimizer_switch
  - optimizer_trace
  - optimizer_trace_features
  - optimizer_trace_limit
  - optimizer_trace_max_mem_size
  - optimizer_trace_offset
  - original_commit_timestamp
  - parser_max_mem_size
  - password_history
  - password_reuse_interval
  - performance_schema_max_digest_sample_age
  - preload_buffer_size
  - profiling_history_size
  - query_alloc_block_size
  - query_prealloc_size
  - range_alloc_block_size
  - range_optimizer_max_mem_size
  - rbr_exec_mode
  - read_buffer_size
  - read_only
  - read_rnd_buffer_size
  - regexp_stack_limit
  - regexp_time_limit
  - relay_log_purge
  - relay_log_recovery
  - replicate-do-db
  - replicate-do-table
  - replicate-ignore-db
  - replicate-ignore-table
  - replicate-wild-do-table
  - replicate-wild-ignore-table
  - require_secure_transport
  - resultset_metadata
  - rpl_read_size
  - rpl_semi_sync_master_wait_for_slave_count
  - rpl_semi_sync_master_wait_point
  - rpl_stop_slave_timeout
  - schema_definition_cache
  - server_id
  - session_track_gtids
  - session_track_schema
  - session_track_state_change
  - session_track_system_variables
  - session_track_transaction_info
  - sha256_password_proxy_users
  - show_create_table_verbosity
  - show_old_temporals
  - slave_allow_batching
  - slave_checkpoint_group
  - slave_checkpoint_period
  - slave_compressed_protocol
  - slave_exec_mode
  - slave_net_timeout
  - slave_parallel_workers
  - slave_pending_jobs_size_max
  - slave_preserve_commit_order
  - slave_rows_search_algorithms
  - slave_sql_verify_checksum
  - slave_transaction_retries
  - slow_launch_time
  - slow_query_log
  - slow_query_log_file
  - sort_buffer_size
  - sql_auto_is_null
  - sql_big_selects
  - sql_buffer_result
  - sql_log_off
  - sql_mode
  - sql_notes
  - sql_quote_show_create
  - sql_require_primary_key
  - sql_safe_updates
  - sql_select_limit
  - sql_slave_skip_counter
  - sql_warnings
  - ssl_fips_mode
  - stored_program_cache
  - stored_program_definition_cache
  - super_read_only
  - sync_binlog
  - sync_master_info
  - sync_relay_log
  - sync_relay_log_info
  - table_definition_cache
  - table_open_cache
  - tablespace_definition_cache
  - temptable_max_ram
  - thread_cache_size
  - time_zone
  - tls_ciphersuites
  - tmp_table_size
  - transaction_alloc_block_size
  - transaction_isolation
  - transaction_prealloc_size
  - transaction_write_set_extraction
  - unique_checks
  - updatable_views_with_limit
  - validate_password_length
  - validate_password_mixed_case_count
  - validate_password_number_count
  - validate_password_policy
  - validate_password_special_char_count
  - wait_timeout
  - windowing_use_high_precision

immutableParameters:
  - allow-suspicious-udfs
  - auto_generate_certs
  - basedir
  - bind_address
  - binlog_direct_non_transactional_updates
  - caching_sha2_password_auto_generate_rsa_keys
  - caching_sha2_password_private_key_path
  - caching_sha2_password_public_key_path
  - character_sets_dir
  - core-file
  - datadir
  - default_authentication_plugin
  - default_time_zone
  - disabled_storage_engines
  - gtid_mode
  - gtid_owned
  - gtid_purged
  - init_file
  - innodb_data_file_path
  - innodb_data_home_dir
  - innodb_directories
  - innodb_doublewrite
  - innodb_force_load_corrupted
  - innodb_force_recovery
  - innodb_log_files_in_group
  - innodb_log_group_home_dir
  - innodb_page_size
  - innodb_read_only
  - innodb_scan_directories
  - innodb_temp_data_file_path
  - innodb_undo_tablespaces
  - large_pages
  - log_bin
  - log-bin
  - log_bin_basename
  - log_bin_index
  - log_slave_updates
  - lower_case_file_system
  - mecab_rc_file
  - mysqlx_bind_address
  - mysqlx_port
  - mysqlx_port_open_timeout
  - mysqlx_socket
  - mysqlx_ssl_ca
  - mysqlx_ssl_capath
  - mysqlx_ssl_cert
  - mysqlx_ssl_crl
  - mysqlx_ssl_crlpath
  - mysqlx_ssl_key
  - open_files_limit
  - persisted_globals_load
  - pid_file
  - plugin_dir
  - port
  - protocol_version
  - relay_log
  - relay-log
  - relay_log_basename
  - relay_log_index
  - relay_log_info_file
  - relay_log_space_limit
  - report_host
  - report_password
  - report_port
  - report_user
  - secure_file_priv
  - server_id
  - sha256_password_auto_generate_rsa_keys
  - sha256_password_private_key_path
  - sha256_password_public_key_path
  - skip_external_locking
  - skip-slave-start
  - slave_load_tmpdir
  - socket
  - ssl_key
  - system_time_zone
  - thread_handling
  - tmpdir
  - validate_password_dictionary_file
  - version_comment
  - version_compile_machine
  - version_compile_os
  - version_compile_zlib
