# permissions for end users to view reconciliationviewdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: reconciliationviewdefinition-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeblocks
    app.kubernetes.io/part-of: kubeblocks
    app.kubernetes.io/managed-by: kustomize
  name: reconciliationviewdefinition-viewer-role
rules:
- apiGroups:
  - view.kubeblocks.io
  resources:
  - reconciliationviewdefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - view.kubeblocks.io
  resources:
  - reconciliationviewdefinitions/status
  verbs:
  - get
