# permissions for end users to edit replicatedstatemachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: replicatedstatemachine-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeblocks
    app.kubernetes.io/part-of: kubeblocks
    app.kubernetes.io/managed-by: kustomize
  name: replicatedstatemachine-editor-role
rules:
- apiGroups:
  - workloads.kubeblocks.io
  resources:
  - replicatedstatemachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.kubeblocks.io
  resources:
  - replicatedstatemachines/status
  verbs:
  - get
