{{- if has "victoria-metrics-agent" .Values.autoInstalledAddons  }}
{{- $imageRegistry := include "kubeblocks.imageRegistry" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-agent-chart-kubeblocks-values
  labels:
    {{- include "kubeblocks.labels" . | nindent 4 }}
  {{- if .Values.keepAddons }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  values-kubeblocks-override.yaml: |-
     {{- .Values.vmagent | toYaml | nindent 4 }}
{{- end }}