annotations:
  artifacthub.io/changes: ""
  artifacthub.io/links: ""
  artifacthub.io/operator: "true"
  artifacthub.io/prerelease: "true"
apiVersion: v2
appVersion: 0.6.3
description: KubeBlocks Core Controller Operator.
home: https://www.kubeblocks.io/
icon: https://kubeblocks.io/img/logo.png
keywords:
  - kubernetes
  - database
  - streaming
  - message queue
  - dbpaas
  - platform
kubeVersion: '>=1.22.0-0'
maintainers:
  - name: ApeCloud
    url: https://github.com/apecloud/kubeblocks/
name: kubeblocks
sources:
  - https://github.com/apecloud/kubeblocks/
type: application
version: 0.6.3
