# permissions for end users to edit backuptools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeblocks.fullname" . }}-backuptool-editor-role
  labels:
    {{- include "kubeblocks.labels" . | nindent 4 }}
rules:
- apiGroups:
  - dataprotection.infracreate.com
  resources:
  - backuptools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataprotection.infracreate.com
  resources:
  - backuptools/status
  verbs:
  - get
