# permissions for end users to edit nodecountscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeblocks.labels" . | nindent 4 }}
  annotations:
    {{- include "kubeblocks.keepResource" . | nindent 4 }}
  name: {{ include "kubeblocks.fullname" . }}-nodecountscaler-editor-role
rules:
- apiGroups:
  - experimental.kubeblocks.io
  resources:
  - nodecountscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experimental.kubeblocks.io
  resources:
  - nodecountscalers/status
  verbs:
  - get
