# permissions for end users to view replicatedstatemachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: replicatedstatemachine-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeblocks
    app.kubernetes.io/part-of: kubeblocks
    app.kubernetes.io/managed-by: kustomize
  name: replicatedstatemachines-viewer-role
rules:
- apiGroups:
  - workloads.kubeblocks.io
  resources:
  - replicatedstatemachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workloads.kubeblocks.io
  resources:
  - replicatedstatemachines/status
  verbs:
  - get
