apiVersion: apps.kubeblocks.io/v1
kind: ComponentVersion
metadata:
  labels:
    app.kubernetes.io/name: componentversion
    app.kubernetes.io/instance: componentversion-sample
    app.kubernetes.io/part-of: kubeblocks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubeblocks
  name: componentversion-sample
spec:
  # TODO(user): Add fields here
