apiVersion: monitor.kubeblocks.io/v1alpha1
kind: OTeld
metadata:
  labels:
    app.kubernetes.io/name: oteld
    app.kubernetes.io/instance: oteld-sample
    app.kubernetes.io/part-of: kubeblocks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubeblocks
  name: oteld-sample
spec:
  # TODO(user): Add fields here
