apiVersion: workloads.kubeblocks.io/v1alpha1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: instance
    app.kubernetes.io/instance: instance-sample
    app.kubernetes.io/part-of: kubeblocks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubeblocks
  name: instance-sample
spec:
  # TODO(user): Add fields here
