{{- include "kblib.clusterCommon" . }}
  clusterDefinitionRef: redis  # ref clusterDefinition.name
  componentSpecs:
    - name: redis
      componentDefRef: redis # ref clusterDefinition componentDefs.name
      {{- include "kblib.componentMonitor" . | indent 6 }}
      {{- include "redis-cluster.replicaCount" . | indent 6 }}
      enabledLogs:
        - running
      serviceAccountName: {{ include "kblib.serviceAccountName" . }}
      switchPolicy:
        type: Noop
      {{- include "kblib.componentResources" . | indent 6 }}
    {{- if eq .Values.mode "replication" }}
    {{- include "redis-cluster.sentinel" . | indent 4 }}
    {{- end }}
