apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: pulsar-zookeeper
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
spec:
  type: zookeeper
  connectionCredential:
    username: ""
    password: ""
    endpoint: "$(SVC_FQDN)"
    port: "$(SVC_PORT_client)"
  componentDefs:
    - name: zookeeper
      workloadType: Stateful
      characterType: zookeeper
      statefulSpec:
        updateStrategy: BestEffortParallel
      monitor:
        builtIn: false
        exporterConfig:
          scrapePath: /metrics
          scrapePort: {{ .Values.metrics.service.port }}
      configSpecs:
        - name: agamotto-configuration
          templateRef: {{ include "pulsar.name" . }}-agamotto-conf-tpl
          namespace: {{ .Release.Namespace }}
          volumeName: agamotto-configuration
        - name: zookeeper-env
          templateRef: {{ include "pulsar.name" . }}-zookeeper-env-tpl
          namespace: {{ .Release.Namespace }}
          volumeName: zookeeper-config-env
          constraintRef: pulsar-env-constraints
          keys:
            - conf
          asEnvFrom:
            - zookeeper
      scriptSpecs:
        - name: pulsar-scripts
          templateRef: {{ include "pulsar.name" . }}-scripts
          namespace: {{ .Release.Namespace }}
          volumeName: scripts
          defaultMode: 0555
      service:
        ports:
          - name: client
            port: 2181
            targetPort: client
      podSpec:
        securityContext:
          fsGroup: 0
          runAsGroup: 0
          runAsNonRoot: true
          runAsUser: 10000
        containers:
          - name: zookeeper
            command:
              - /kb-scripts/start-zookeeper.sh
            env:
              {{- if .Values.debugEnabled }}
              - name: PULSAR_LOG_ROOT_LEVEL
                value: DEBUG
              - name: PULSAR_LOG_LEVEL
                value: DEBUG
              {{- end }}
              - name: EXTERNAL_PROVIDED_SERVERS
                value: "false"
              - name: OPTS
                value: "-Dlog4j2.formatMsgNoLookups=true"
            ports:
              - name: client
                containerPort: 2181
              - name: tcp-quorum
                containerPort: 2888
              - name: tcp-election
                containerPort: 3888
              - name: http
                containerPort: 8000
            livenessProbe:
              exec:
                command:
                  - bash
                  - -c
                  - echo ruok | nc -q 1 localhost 2181 | grep imok
              failureThreshold: 10
              initialDelaySeconds: 5
              periodSeconds: 30
              successThreshold: 1
              timeoutSeconds: 30
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              privileged: false
              runAsGroup: 0
              runAsNonRoot: true
              runAsUser: 10000
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /pulsar/data
                name: data
              - mountPath: /pulsar/data-log
                name: data-log
              - name: scripts
                mountPath: /kb-scripts
              - name: zookeeper-config-env
                mountPath: /opt/pulsar/none
          - name: metrics
            image: {{ .Values.images.metrics.repository }}:{{ .Values.images.metrics.tag }}
            imagePullPolicy: {{ default "IfNotPresent" .Values.images.metrics.pullPolicy }}
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
            env:
              - name: JOB_NAME
                value: zookeeper
              - name: SERVICE_PORT
                value: "8000"
              - name: POD_NAME
                value: $(KB_POD_NAME)
              - name: POD_NAMESPACE
                value: $(KB_NAMESPACE)
              {{- if .Values.debugEnabled }}
              - name: LOG_LEVEL
                value: debug
              {{- else }}
              - name: LOG_LEVEL
                value: info
              {{- end }}
            command:
              - "/bin/agamotto"
              - "--config=/opt/agamotto/agamotto-config.yaml"
              - "--feature-gates=-pkg.translator.prometheus.NormalizeName"
            ports:
              - name: http-metrics
                containerPort: {{ .Values.metrics.service.port }}
            volumeMounts:
              - name: agamotto-configuration
                mountPath: /opt/agamotto
