---
# Source: kubeblocks/templates/applications/snapshot-controller-addon.yaml
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: snapshot-controller
  labels:
    helm.sh/chart: kubeblocks-0.8.0-alpha.0
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.8.0-alpha.0"
    app.kubernetes.io/managed-by: Helm
    "kubeblocks.io/provider": community
spec:
  description: 'Deploys a Snapshot Controller in a cluster. Snapshot Controllers are
    often bundled with the Kubernetes distribution, this chart is meant for cases where
    it is not. '
  type: Helm

  helm:    
    chartLocationURL: file:///snapshot-controller-1.7.2.tgz    
    chartsImage: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/kubeblocks-charts:0.8.0-alpha.0
    chartsPathInImage: /charts

    installOptions:

    installValues:
      configMapRefs:
        - name: snapshot-controller-chart-kubeblocks-values
          key: values-kubeblocks-override.yaml

    valuesMapping:
      valueMap:
        replicaCount: replicaCount
        storageClass: volumeSnapshotClasses[0].driver

      jsonMap:
        tolerations: tolerations

      resources:
        cpu:
          requests: resources.requests.cpu
          limits: resources.limits.cpu
        memory:
          requests: resources.requests.memory
          limits: resources.limits.memory

  defaultInstallValues:
    - enabled: true
      tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"

    - selectors:
        - key: KubeGitVersion
          operator: Contains
          values:
            - eks
      storageClass: ebs.csi.aws.com
      tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"

    - selectors:
        - key: KubeGitVersion
          operator: Contains
          values:
            - gke
      storageClass: pd.csi.storage.gke.io
      tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"

    - selectors:
        - key: KubeGitVersion
          operator: Contains
          values:
            - aks
      storageClass: disk.csi.azure.com
      tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"

  installable:
    autoInstall:  true
    selectors:
      - key: KubeGitVersion
        operator: DoesNotContain
        values:
          - tke
          - aliyun.
      - key: KubeProvider
        operator: DoesNotContain
        values:
          - huaweiCloud
          - azure
