# Default values for foxlake.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


clusterVersionOverride: ""

## @param application images
##
images:
  pullPolicy: IfNotPresent
  foxlake:
    repository: apecloud/foxlake
    pullPolicy: Always
    tag: "main"
  mysql:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: "latest"
  minio:
    repository: docker.io/minio/minio
    tag: RELEASE.2022-03-17T06-34-49Z

## @param storage configuration
##
s3:
  accessKey: ""
  secretKey: ""
  defaultRegion: ""
minio:
  accessKey: "rootuser"
  secretKey: "rootpass123"