# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/apps.kubeblocks.io_backuppolicytemplates.yaml
- bases/apps.kubeblocks.io_clusters.yaml
- bases/apps.kubeblocks.io_clusterdefinitions.yaml
- bases/apps.kubeblocks.io_clusterversions.yaml
- bases/apps.kubeblocks.io_configconstraints.yaml
- bases/apps.kubeblocks.io_opsrequests.yaml
- bases/dataprotection.kubeblocks.io_backuptools.yaml
- bases/dataprotection.kubeblocks.io_backuppolicies.yaml
- bases/dataprotection.kubeblocks.io_backups.yaml
- bases/dataprotection.kubeblocks.io_restorejobs.yaml
- bases/extensions.kubeblocks.io_addons.yaml
- bases/apps.kubeblocks.io_classfamilies.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_clusters.yaml
#- patches/webhook_in_clusterdefinitions.yaml
#- patches/webhook_in_clusterversions.yaml
#- patches/webhook_in_backuptools.yaml
#- patches/webhook_in_backuppolicies.yaml
#- patches/webhook_in_backups.yaml
#- patches/webhook_in_restorejobs.yaml
#- patches/webhook_in_backuppolicytemplates.yaml
#- patches/webhook_in_opsrequests.yaml
#- patches/webhook_in_reconfigurerequests.yaml
#- patches/webhook_in_configconstraints.yaml
#- patches/webhook_in_hostpreflights.yaml
#- patches/webhook_in_preflights.yaml
#- patches/webhook_in_addons.yaml
#- patches/webhook_in_classfamilies.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_clusters.yaml
#- patches/cainjection_in_clusterdefinitions.yaml
#- patches/cainjection_in_clusterversions.yaml
#- patches/cainjection_in_backuptools.yaml
#- patches/cainjection_in_backuppolicies.yaml
#- patches/cainjection_in_backups.yaml
#- patches/cainjection_in_restorejobs.yaml
#- patches/cainjection_in_backuppolicytemplates.yaml
#- patches/cainjection_in_opsrequests.yaml
#- patches/cainjection_in_reconfigurerequests.yaml
#- patches/cainjection_in_configconstraints.yaml
#- patches/cainjection_in_hostpreflights.yaml
#- patches/cainjection_in_preflights.yaml
#- patches/cainjection_in_addonspecs.yaml
#- patches/cainjection_in_classfamilies.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
