# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/apps.kubeblocks.io_backuppolicytemplates.yaml
- bases/apps.kubeblocks.io_clusters.yaml
- bases/apps.kubeblocks.io_clusterdefinitions.yaml
- bases/apps.kubeblocks.io_clusterversions.yaml
- bases/apps.kubeblocks.io_configconstraints.yaml
- bases/apps.kubeblocks.io_opsrequests.yaml
- bases/dataprotection.kubeblocks.io_actionsets.yaml
- bases/dataprotection.kubeblocks.io_backupschedules.yaml
- bases/dataprotection.kubeblocks.io_backuppolicies.yaml
- bases/dataprotection.kubeblocks.io_backups.yaml
- bases/extensions.kubeblocks.io_addons.yaml
- bases/apps.kubeblocks.io_componentresourceconstraints.yaml
- bases/apps.kubeblocks.io_componentclassdefinitions.yaml
- bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
- bases/storage.kubeblocks.io_storageproviders.yaml
- bases/dataprotection.kubeblocks.io_backuprepos.yaml
- bases/dataprotection.kubeblocks.io_restores.yaml
- bases/apps.kubeblocks.io_configurations.yaml
- bases/apps.kubeblocks.io_servicedescriptors.yaml
- bases/apps.kubeblocks.io_componentdefinitions.yaml
- bases/apps.kubeblocks.io_components.yaml
- bases/apps.kubeblocks.io_opsdefinitions.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_clusters.yaml
#- patches/webhook_in_clusterdefinitions.yaml
#- patches/webhook_in_clusterversions.yaml
#- patches/webhook_in_backuptools.yaml
#- patches/webhook_in_backuppolicies.yaml
#- patches/webhook_in_backups.yaml
#- patches/webhook_in_backuppolicytemplates.yaml
#- patches/webhook_in_opsrequests.yaml
#- patches/webhook_in_reconfigurerequests.yaml
#- patches/webhook_in_configconstraints.yaml
#- patches/webhook_in_hostpreflights.yaml
#- patches/webhook_in_preflights.yaml
#- patches/webhook_in_addons.yaml
#- patches/webhook_in_componentresourceconstraints.yaml
#- patches/webhook_in_componentclassdefinitions.yaml
#- patches/webhook_in_replicatedstatemachines.yaml
#- patches/webhook_in_storageproviders.yaml
#- patches/webhook_in_backuprepos.yaml
#- patches/webhook_in_restores.yaml
#- patches/webhook_in_configurations.yaml
#- patches/webhook_in_servicedescriptors.yaml
#- patches/webhook_in_componentdefinitions.yaml
#- patches/webhook_in_components.yaml
#- patches/webhook_in_opsdefinitions.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_clusters.yaml
#- patches/cainjection_in_clusterdefinitions.yaml
#- patches/cainjection_in_clusterversions.yaml
#- patches/cainjection_in_backuptools.yaml
#- patches/cainjection_in_backuppolicies.yaml
#- patches/cainjection_in_backups.yaml
#- patches/cainjection_in_backuppolicytemplates.yaml
#- patches/cainjection_in_opsrequests.yaml
#- patches/cainjection_in_reconfigurerequests.yaml
#- patches/cainjection_in_configconstraints.yaml
#- patches/cainjection_in_hostpreflights.yaml
#- patches/cainjection_in_preflights.yaml
#- patches/cainjection_in_addonspecs.yaml
#- patches/cainjection_in_componentresourceconstraints.yaml
#- patches/cainjection_in_componentclassdefinitions.yaml
#- patches/cainjection_in_replicatedstatemachines.yaml
#- patches/cainjection_in_storageproviders.yaml
#- patches/cainjection_in_backuprepos.yaml
#- patches/cainjection_in_restores.yaml
#- patches/cainjection_in_configurations.yaml
#- patches/cainjection_in_servicedescriptors.yaml
#- patches/cainjection_in_componentdefinitions.yaml
#- patches/cainjection_in_components.yaml
#- patches/cainjection_in_opsdefinitions.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
