---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: parameters.parameters.kubeblocks.io
spec:
  group: parameters.kubeblocks.io
  names:
    categories:
    - kubeblocks
    kind: Parameter
    listKind: ParameterList
    plural: parameters
    singular: parameter
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: cluster name
      jsonPath: .spec.clusterName
      name: CLUSTER
      type: string
    - description: config status phase.
      jsonPath: .status.phase
      name: STATUS
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Parameter is the Schema for the parameters API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ParameterSpec defines the desired state of Parameter
            properties:
              clusterName:
                description: Specifies the name of the Cluster resource that this
                  operation is targeting.
                type: string
                x-kubernetes-validations:
                - message: forbidden to update spec.clusterName
                  rule: self == oldSelf
              componentParameters:
                description: Lists ComponentParametersSpec objects, each specifying
                  a Component and its parameters and template updates.
                items:
                  properties:
                    componentName:
                      description: Specifies the name of the Component.
                      type: string
                    parameters:
                      additionalProperties:
                        type: string
                      description: Specifies the user-defined configuration template
                        or parameters.
                      type: object
                    userConfigTemplates:
                      additionalProperties:
                        properties:
                          namespace:
                            default: default
                            description: |-
                              Specifies the namespace of the referenced configuration template ConfigMap object.
                              An empty namespace is equivalent to the "default" namespace.
                            pattern: ^[a-z0-9]([a-z0-9\-]*[a-z0-9])?$
                            type: string
                          policy:
                            default: none
                            description: Defines the strategy for merging externally
                              imported templates into component templates.
                            enum:
                            - patch
                            - replace
                            - none
                            type: string
                          templateRef:
                            description: Specifies the name of the referenced configuration
                              template ConfigMap object.
                            pattern: ^[a-z0-9]([a-z0-9\.\-]*[a-z0-9])?$
                            type: string
                        required:
                        - templateRef
                        type: object
                      description: |-
                        Specifies the user-defined configuration template.


                        When provided, the `importTemplateRef` overrides the default configuration template
                        specified in `configSpec.templateRef`.
                        This allows users to customize the configuration template according to their specific requirements.
                      type: object
                  required:
                  - componentName
                  type: object
                type: array
            required:
            - componentParameters
            type: object
          status:
            description: ParameterStatus defines the observed state of Parameter
            properties:
              componentReconfiguringStatus:
                description: Records the status of a reconfiguring operation if `opsRequest.spec.type`
                  equals to "Reconfiguring".
                items:
                  properties:
                    componentName:
                      description: Specifies the name of the Component.
                      type: string
                    parameterStatus:
                      description: Describes the status of the component reconfiguring.
                      items:
                        properties:
                          lastDoneRevision:
                            description: Represents the last completed revision of
                              the configuration item. This field is optional.
                            type: string
                          message:
                            description: Provides a description of any abnormal status.
                              This field is optional.
                            type: string
                          name:
                            description: |-
                              Specifies the name of the configuration template. It is a required field and must be a string of maximum 63 characters.
                              The name should only contain lowercase alphanumeric characters, hyphens, or periods. It should start and end with an alphanumeric character.
                            maxLength: 63
                            pattern: ^[a-z0-9]([a-z0-9\.\-]*[a-z0-9])?$
                            type: string
                          phase:
                            description: |-
                              Indicates the current status of the configuration item.


                              Possible values include "Creating", "Init", "Running", "Pending", "Merged", "MergeFailed", "FailedAndPause",
                              "Upgrading", "Deleting", "FailedAndRetry", "Finished".
                            enum:
                            - Creating
                            - Init
                            - Running
                            - Pending
                            - Merged
                            - MergeFailed
                            - FailedAndPause
                            - Upgrading
                            - Deleting
                            - FailedAndRetry
                            - Finished
                            type: string
                          reconcileDetail:
                            description: Provides detailed information about the execution
                              of the configuration change. This field is optional.
                            properties:
                              currentRevision:
                                description: Represents the current revision of the
                                  configuration item.
                                type: string
                              errMessage:
                                description: Represents the error message generated
                                  when the execution of configuration changes fails.
                                type: string
                              execResult:
                                description: Represents the outcome of the most recent
                                  execution.
                                type: string
                              expectedCount:
                                default: -1
                                description: Represents the total number of pods that
                                  require execution of configuration changes.
                                format: int32
                                type: integer
                              policy:
                                description: Represents the policy applied during
                                  the most recent execution.
                                type: string
                              succeedCount:
                                default: -1
                                description: Represents the number of pods where configuration
                                  changes were successfully applied.
                                format: int32
                                type: integer
                            type: object
                          updateRevision:
                            description: Represents the updated revision of the configuration
                              item. This field is optional.
                            type: string
                          updatedParameters:
                            additionalProperties:
                              properties:
                                content:
                                  description: |-
                                    Holds the configuration keys and values. This field is a workaround for issues found in kubebuilder and code-generator.
                                    Refer to https://github.com/kubernetes-sigs/kubebuilder/issues/528 and https://github.com/kubernetes/code-generator/issues/50 for more details.


                                    Represents the content of the configuration file.
                                  type: string
                                parameters:
                                  additionalProperties:
                                    type: string
                                  description: Represents the updated parameters for
                                    a single configuration file.
                                  type: object
                              type: object
                            description: Contains the updated parameters.
                            type: object
                          userConfigTemplates:
                            description: |-
                              Specifies the user-defined configuration template.


                              When provided, the `importTemplateRef` overrides the default configuration template
                              specified in `configSpec.templateRef`.
                              This allows users to customize the configuration template according to their specific requirements.
                            properties:
                              namespace:
                                default: default
                                description: |-
                                  Specifies the namespace of the referenced configuration template ConfigMap object.
                                  An empty namespace is equivalent to the "default" namespace.
                                pattern: ^[a-z0-9]([a-z0-9\-]*[a-z0-9])?$
                                type: string
                              policy:
                                default: none
                                description: Defines the strategy for merging externally
                                  imported templates into component templates.
                                enum:
                                - patch
                                - replace
                                - none
                                type: string
                              templateRef:
                                description: Specifies the name of the referenced
                                  configuration template ConfigMap object.
                                pattern: ^[a-z0-9]([a-z0-9\.\-]*[a-z0-9])?$
                                type: string
                            required:
                            - templateRef
                            type: object
                        required:
                        - name
                        type: object
                      type: array
                      x-kubernetes-list-map-keys:
                      - name
                      x-kubernetes-list-type: map
                    phase:
                      description: |-
                        Indicates the current status of the configuration item.


                        Possible values include "Creating", "Init", "Running", "Pending", "Merged", "MergeFailed", "FailedAndPause",
                        "Upgrading", "Deleting", "FailedAndRetry", "Finished".
                      enum:
                      - Creating
                      - Init
                      - Running
                      - Pending
                      - Merged
                      - MergeFailed
                      - FailedAndPause
                      - Upgrading
                      - Deleting
                      - FailedAndRetry
                      - Finished
                      type: string
                  required:
                  - componentName
                  type: object
                type: array
              message:
                description: Provides a description of any abnormal status.
                type: string
              observedGeneration:
                description: |-
                  Represents the latest generation observed for this
                  ClusterDefinition. It corresponds to the ConfigConstraint's generation, which is
                  updated by the API Server.
                format: int64
                type: integer
              phase:
                description: |-
                  Indicates the current status of the configuration item.


                  Possible values include "Creating", "Init", "Running", "Pending", "Merged", "MergeFailed", "FailedAndPause",
                  "Upgrading", "Deleting", "FailedAndRetry", "Finished".
                enum:
                - Creating
                - Init
                - Running
                - Pending
                - Merged
                - MergeFailed
                - FailedAndPause
                - Upgrading
                - Deleting
                - FailedAndRetry
                - Finished
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
