name: PR-TIMER
on:
  schedule:
    - cron: '55 1 * * 3' #Runs at 06:06 UTC on Mon

jobs:
  calculate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run simple-pr-stats
        uses: akwodkiewicz/simple-pr-stats@v0.2
        with:
          token: ${{ secrets.KUBEBLOCKS_TOKEN }}
          days_back: 40
      - name: Run all-pr-stats
        uses: akwodkiewicz/simple-pr-stats@v0.2
        with:
          token: ${{ secrets.KUBEBLOCKS_TOKEN }}
          days_back: 360    
